### PR TITLE
Add helper-live2d plugin

### PR DESCRIPTION
**Pull request by JoeyBling**
> https://github.com/JoeyBling/vuepress-plugin-helper-live2d

### CODE REVIEW

**Comment by meteorlxy** [comment]
Thanks for your contribution~

But this project only includes documentations of packages that maintained by @vuepress group

**Comment by JoeyBling** [comment]
> Thanks for your contribution~
> 
> But this project only includes documentations of packages that maintained by @vuepress group

Haha ha, well, I think it's a community, okay.
So, how can i display your own plug-ins or themes on the official website, just like Hexo's official website?

**Comment by meteorlxy** [comment]
@JoeyBling 

Awesome projects ~

https://github.com/ulivz/awesome-vuepress

(I have ever created [another one](https://github.com/meteorlxy/awesome-vuepress) but has been deprecated)

**Comment by JoeyBling** [comment]
@meteorlxy great,thanks

**Comment by JoeyBling** [comment]
@meteorlxy Why only English, no Chinese

**Comment by meteorlxy** [comment]
Both 语言都 ok 啊 😄 

PR 先关啦，你可以把文档放到自己项目的 github pages 里

**Comment by JoeyBling** [comment]
Is it just a `markdown` document to maintain?

**Comment by meteorlxy** [comment]
是的，链接到各个项目的 repo 页或者文档页

**Comment by JoeyBling** [comment]
@meteorlxy 好的，谢谢你了

**Comment by meteorlxy** [comment]
（其实我之前也想做个 live2d 的插件来着，不过后来没仔细研究。以后想用就找你问啦，哈哈）

**Comment by JoeyBling** [comment]
自己封装了一点js，其他的调用的`live2d`官方的库，哈哈，谢啦

**Pull request closed without merging**
